version: "2"
services:
  blog:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - "./var/lib/ghost:/var/lib/ghost"
      environment:
          URI_BASE: http://localhost:2368

  proxy:
      build:
        context: ./proxy
        dockerfile: Dockerfile
      links:
        - blog
      ports:
        - "2368:2368"
      volumes:
        - "caddy:/root/.caddy"
      environment:
        CADDY_PROXY_DOMAINS: "localhost:2368"
        CADDY_PROXY_TO: "blog:2368"
        CADDY_STATS: "on"
        CADDY_TLS: "off"

volumes:
  content: {}
  caddy: {}
