version: "3.1"

services:

  blog:
      build: ./Dockerfile
      restart: always
      ports:
        - 2368:2368
      volumes:
        - "./src/content/themes/bunk:/var/lib/ghost/content/themes/bunk"
