blog:
    build: .
    volumes:
        - "./src/content:/var/lib/ghost"
    environment:
        URI_BASE: http://localhost:2387

caddy:
    image: bunk/blog-caddy
    links:
        - blog
    volumes:
        - "./Caddyfile:/etc/Caddyfile"
    ports:
        - "2387:2387"
